name: micro_ddd
description: A minimalist library of Domain Driven Design tools.
version: 1.1.0
homepage: https://github.com/Spyryto/micro_ddd

environment:
  sdk: '>=2.14.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
